//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamDBEntities : DbContext
    {
        public ExamDBEntities()
            : base("name=ExamDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<Test_Details> Test_Details { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    }
}
