//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Details
    {
        public int Id { get; set; }
        public string Test_Id { get; set; }
        public short Total_Questions { get; set; }
        public short Total_Marks { get; set; }
        public double Correct_Mark { get; set; }
        public double Wrong_Mark { get; set; }
        public string Course { get; set; }
        public byte Semester { get; set; }
        public byte Status { get; set; }
        public System.DateTime Date { get; set; }
        public string Duration { get; set; }
        public string Passing_Mark { get; set; }
    }
}
